name: Test and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Cache dependencies
        uses: actions/setup-node@v4
        with:
          # `actions/setup-node` can be configured to not set up Node.js by omitting the `node-version` field
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Playground Build
        run: cd playground && pnpm build

      - name: Playground Test
        run: |
          cd playground
          docker compose up -d
          pnpm test
          docker compose down

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changesets-version
          publish: pnpm changesets-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"

      - name: Update Release PR
        if: steps.changesets.outputs.pullRequestNumber != ''
        continue-on-error: true
        run: |
          VERSION=$(jq -r '.version' package.json)
          gh pr edit "${{ steps.changesets.outputs.pullRequestNumber }}" --title "Release v$VERSION" --add-label release

      - name: Upload Test Results if VRT failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: VRT Results
          path: playground/test-results
          retention-days: 7
