name: Test on push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: ./playground
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Cache dependencies
        uses: actions/setup-node@v4
        with:
          # `actions/setup-node` can be configured to not set up Node.js by omitting the `node-version` field
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      # This step is required to pass type-checking
      - name: Prebuild
        run: pnpm vite build

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Playground Build
        run: cd playground && pnpm build

      - name: Playground Test
        run: |
          cd playground
          docker compose up -d
          pnpm test:container
          docker compose down

      - name: Upload diffs if VRT failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: VRT diffs
          path: playground/test-results
          retention-days: 7
